In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup as bs
import requests

In [133]:
#import dataframe with API list to scrape
crockett_list = pd.read_csv('Crockett_Corrected_API.csv')
crockett_list = crockett_list.drop(['Unnamed: 0', 
                          'Unnamed: 0.1'], axis = 1)
crockett_list

,Filename,API,LOC,STRT DEPT,TVD,GR,PE,NPHI,DPHI,XPHI,SPHI,LLD,MSFL,RHOB,POTA,Total Logs
0,06_14_APPROACH_UNIVERSITY_42_13_11_FIELD_LAS.las,4210541145,NaN,114.7500,8038.0,1,1,1,1,1,0,1,1,1,0,8
1,08_18_GREATWESTERN_UNIV_31_1_LAS.las,4210542069,950' FNL & 470' FWL,190.0000,9913.5,1,1,1,1,1,1,0,0,1,0,7
2,10502595.las,4210581358,"SECTION 28,BLOCK 5",110.0000,9723.0,1,1,1,1,0,0,1,0,1,0,6
3,10537385.las,4210537385,728' FSL & 491' FEL,8690.0000,11121.0,1,0,0,0,0,0,0,0,0,0,1
4,10537461.las,4210537461,660'FNL & 1320'FWL,74.0000,6864.5,0,0,0,0,0,0,0,0,0,0,0
5,10537507.las,4210537507,2300' FSL & 1050' FEL,184.0000,7794.5,1,0,1,1,0,0,0,0,1,0,4
6,10537798.las,4210537798,NaN,131.5000,8458.0,1,0,1,1,0,0,0,0,1,0,4
7,10537897.las,4210537897,"SECTION 32, BLOCK 7",98.0000,3055.0,1,1,1,1,0,1,1,0,1,1,8
8,10537917.las,4210537917,881' FNL & 1559' FEL,165.0000,8916.0,1,0,1,1,0,1,0,0,1,0,5
9,10541148_APPROACH_UNIVERSITY_45_21_7_FIELD_LAS...,4210541148,NaN,117.2500,8052.0,1,1,1,1,1,0,1,1,1,0,8
10,37507.las,4210537507,2300' FSL & 1050' FEL,8328.5000,10697.0,0,0,1,1,0,0,0,0,1,1,4
11,37635por.las,4210537635,"259 FSL & 2093 FWL,",1982.3334,9175.0,1,1,1,1,0,0,0,0,1,0,5
12,37635res.las,4210537635,"259 FSL & 2093 FWL,",1989.5834,9175.0,1,0,0,0,0,0,0,0,0,0,1
13,37897r.las,4210537897,"SECTION 32, BLOCK 7",2685.0000,3055.0,1,1,1,1,0,0,1,0,1,1,7
14,42-105-41761-0100_University 52-23 #11H ST01_F...,4210541761,NaN,894.0000,14136.0,0,0,0,0,0,0,0,0,0,0,0
15,42-105-41761_University 52-23 #11H_Final Gamma...,4210541761,NaN,894.0000,13110.0,0,0,0,0,0,0,0,0,0,0,0
16,42-105-41933_University 50-15 4H_Gamma.las,4210541933,NaN,1013.0000,11749.0,0,0,0,0,0,0,0,0,0,0,0
17,42-105-41933_University 50-15 4H_Survey.las,4210541933,NaN,0.0000,11749.0,0,0,0,0,0,0,0,0,0,0,0
18,42-105-41963_University 50-15 6H_Final_Gamma.las,4210541963,NaN,1017.0000,11787.0,0,0,0,0,0,0,0,0,0,0,0
19,42-105-41963_University 50-15 6H_Gamma.las,4210541963,NaN,1017.0000,11779.0,0,0,0,0,0,0,0,0,0,0,0
20,42-105-41966_University 46-3 #1H_Final Gamma.las,4210541966,NaN,940.0000,11966.0,0,0,0,0,0,0,0,0,0,0,0
21,42-105-41967_University 47-11 2H_Final_Gamma.las,4210541967,NaN,1683.0000,11811.0,0,0,0,0,0,0,0,0,0,0,0
22,42-105-41967_University 47-11 2H_Final_Survey.las,4210541967,NaN,0.0000,11811.0,0,0,0,0,0,0,0,0,0,0,0
23,42-105-41967_University 47-11 2H_Gamma.las,4210541967,NaN,1683.0000,11811.0,0,0,0,0,0,0,0,0,0,0,0
24,42-105-41967_University 47-11 2H_Survey.las,4210541967,NaN,0.0000,11811.0,0,0,0,0,0,0,0,0,0,0,0
25,42-105-41972_University 50-14 1H_Final Gamma.las,4210541972,NaN,1092.0000,11736.0,0,0,0,0,0,0,0,0,0,0,0
26,42-105-42023_University 47-3 #3H_Final Gamma.las,4210542023,NaN,1047.0000,14589.0,0,0,0,0,0,0,0,0,0,0,0
27,42-105-42024_University 47-4W #1H_Final Gamma.las,4210542024,NaN,1006.0000,14534.0,0,0,0,0,0,0,0,0,0,0,0
28,42-105-42030_University 30-9 3H_Final Gamma.las,4210542030,NaN,960.0000,12742.0,0,0,0,0,0,0,0,0,0,0,0
29,42100541085_APPROACH_UNIVERSITY_45-29_2_TRIPLE...,4210541085,NaN,111.5000,8126.0,1,1,1,1,1,0,1,1,1,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,UNIVERSITY-50-12-W1P_4210542084_ECS-CALIBRATIO...,4210542084,600' FNL & 954' FWL,534.5000,903.0,1,0,1,0,0,0,0,0,0,0,2
991,UNIVERSITY-50-12-W1P_4210542084_GR_final.las,4210542084,600' FNL & 954' FWL,945.0000,7945.0,0,0,0,0,0,0,0,0,0,0,0
992,UNIVERSITY-50-12-W1P_4210542084_SON_SScan-PnS.las,4210542084,600' FNL & 954' FWL,4320.0000,7870.0,1,0,1,0,0,1,0,0,1,0,4
993,UNIVERSITY-50-12-W1P_4210542084_TCOM_4400ft_ru...,4210542084,600' FNL & 954' FWL,4380.5000,7923.5,1,0,1,0,0,0,0,0,0,0,2
994,UNIVERSITY-50-12-W1P_4210542084_TCOM_6000ft_ru...,4210542084,600' FNL & 954' FWL,5980.5000,7923.5,1,0,1,0,0,0,0,0,0,0,2
995,UNIVERSITY-50-14-2H_42105419730000_GR.las,4210541973,Crockett County,977.0000,12107.0,1,0,0,0,0,0,0,0,0,0,1
996,UNIVERSITY-50-14-3H_42105419740000_GR.las,4210541974,NaN,977.0000,11317.0,1,0,0,0,0,0,0,0,0,0,1
997,UNIVERSITY-50-15-4H_42105419330000__GR.las,4210541933,NaN,1013.0000,11749.0,0,0,0,0,0,0,0,0,0,0,0
998,UNIVERSITY-52-23-10H_42105417600000_GR.las,4210541760,NaN,767.0000,14161.0,0,0,0,0,0,0,0,0,0,0,0
999,UNIVERSITY-52-23-11H-ST01_42105417610100_ DIR-...,4210541760,NaN,100.0000,14136.0,0,0,0,0,0,0,0,0,0,0,0
1000,UNIVERSITY-52-23-11H-ST01_42105417610100_ GR.las,4210541761,NaN,894.0000,14136.0,0,0,0,0,0,0,0,0,0,0,0
1001,UNIVERSITY_09_0806H.las,4238339202,1891' FNL 2316' FWL SEC. 8 BLK 9,6400.0000,14808.0,0,0,0,0,0,0,0,0,0,0,0
1002,University_42_#1439HC_LWD_FINAL.las,4210542202,NaN,1214.0000,13444.0,0,0,0,0,0,0,0,0,0,0,0
1003,University_42_1215HC_Gamma_Final.las,4210542185,NaN,5299.0000,16683.0,0,0,0,0,0,0,0,0,0,0,0
1004,University_42_1217HB_Gamma_Final.las,4210542186,NaN,5171.0000,15755.0,0,0,0,0,0,0,0,0,0,0,0
1005,UNIVERSITY_42_1420HC_FINAL_GAMMA.las,4210542237,NaN,1214.0000,14206.0,0,0,0,0,0,0,0,0,0,0,0
1006,UNIVERSITY_42_1440HB_FINAL_GAMMA.las,4210542228,NaN,1214.0000,14590.0,0,0,0,0,0,0,0,0,0,0,0
1007,UNIVERSITY_42_22_5_LAS.las,4210540998,NaN,200.0000,8048.0,1,1,1,1,1,0,1,1,1,0,8
1008,UNIVERSITY_45_2118HC_FINAL_GAMMA.las,4210541981,NaN,5396.0000,14750.0,0,0,0,0,0,0,0,0,0,0,0
1009,University_47_#0806H LAS.las,4210541907,NaN,5282.0000,15575.0,1,0,0,0,0,0,0,0,0,0,1
1010,Universtiy-47-5-1H_42105419920000_GR.las,4210541992,NaN,1162.0000,11775.0,0,0,0,0,0,0,0,0,0,0,0
1011,UNIV_4210542012_45_741HA_.las,4210542012,Crockett County,1344.0000,13702.0,1,0,0,0,0,0,0,0,0,0,1
1012,WARREN_UNIVTEX7_FEB26-MN.las,4210541945,2447' FWL & 1012' FSL,830.0000,2493.0,1,1,0,0,0,0,0,0,1,0,3
1013,WARREN_UNIVTEX7_FEB26-RP.las,4210541945,2447' FWL & 1012' FSL,2107.0000,2493.0,1,1,0,0,0,0,0,0,1,0,3
1014,WARREN_UT233_6_FEB_20_HIRES.las,4210541944,350' FEL & 350' FNL,1900.0000,2477.4,0,0,0,0,0,0,0,0,0,0,0
1015,WARREN_UT233_6_FEB_20_MAIN.las,4210541944,350' FEL & 350' FNL,848.0000,2477.5,1,1,0,0,0,0,0,0,1,0,3
1016,WARREN_UT233_6_FEB_20_RP.las,4210541944,350' FEL & 350' FNL,2132.0000,2477.5,1,1,0,0,0,0,0,0,1,0,3
1017,WARREN_UT245_4_MAR1-MAIN.las,4210541943,350' FEL & 1691' FNL,840.0000,2372.0,1,1,0,0,0,0,0,0,1,0,3
1018,WARREN_UT245_4_MAR1-RPT.las,4210541943,350' FEL & 1691' FNL,1929.0000,2372.5,1,1,0,0,0,0,0,0,1,0,3
1019,WARREN_UT245_6_AUG6_MAIN2.las,4210542255,1720' FEL & 2320' FNL,705.0000,2348.0,1,1,0,0,0,0,0,0,1,0,3

In [134]:
reagan_list = pd.read_csv('Reagan_Corrected_API_Values.csv')
reagan_list = reagan_list.drop(['Unnamed: 0', 
                                'Unnamed: 0.1'], axis = 1)
reagan_list

,Filename,API,LOC,GR,PE,NPHI,DPHI,XPHI,SPHI,LLD,MSFL,RHOB,POTA
0,34779dn.las,4238334779,SEC7-6-ULS 467'S/1890'W,1,1,1,1,0,0,0,0,1,0
1,34779r.las,4238334779,SEC7-6-ULS 467'S/1890'W,1,0,0,0,0,0,0,0,0,0
2,34779s.las,4238334779,SEC7-6-ULS 467'S/1890'W,1,0,0,0,0,1,0,0,0,0
3,34800r2.las,4238334800,"SECTION 18, BLOCK 6",1,1,1,1,0,1,1,0,1,0
4,34800rs1.las,4238334800,"SECTION 18, BLOCK 6",1,0,0,0,0,1,0,0,0,0
5,34800rs2.las,4238334800,"SECTION 18, BLOCK 6",1,0,0,0,0,1,0,0,0,0
6,34814son.las,4238334814,823' FNL & 1528' FWL,1,0,0,0,0,1,0,0,0,0
7,34815por.las,4238334815,1845' FNL & 1980' FW,1,0,1,1,0,1,0,0,1,0
8,34815res.las,4238334815,1845' FNL & 1980' FW,1,0,0,0,0,0,0,0,0,0
9,34829p.las,4238334829,1962' FNL & 1597' FE,1,0,1,1,0,1,0,0,1,1
10,34829r.las,4238334829,1962' FNL & 1597' FE,1,0,0,0,0,0,0,0,0,0
11,34871rep.las,4238334871,"SECTION 18, BLOCK 6",1,1,1,1,0,1,0,0,1,0
12,34872res.las,4238334872,636' FNL & 468' FEL,1,0,0,0,0,0,0,0,0,0
13,34872son.las,4238334872,636' FNL & 468' FEL,1,0,0,0,0,1,0,0,0,0
14,34917por.las,4238334917,2480' FSL & 467' FEL,0,0,1,0,0,0,0,0,0,1
15,34917rst.las,4238334917,2480' FSL & 467' FEL,1,0,0,0,0,0,0,0,0,0
16,35079son.las,4238335079,Sec. 6 Blk. 7 ULS,1,0,1,1,0,1,1,0,1,0
17,38334746.las,4238334746,"SECTION 7,BLOCK6",1,1,1,1,0,1,0,0,1,0
18,38334774.las,4230334774,SECTION 17,1,1,1,1,0,1,0,0,1,0
19,38334785.las,4238334785,1100' FSL & 1212' FW,1,0,1,1,0,0,0,0,1,0
20,38334800.las,4238334800,"SECTION 18, BLOCK 6",1,1,1,1,0,1,1,0,1,0
21,38334814.las,4238334814,823' FNL & 1528' FWL,1,0,1,1,0,0,0,0,1,0
22,38334861.las,4238334861,"SECTION 6, BLOCK 7",1,1,1,1,1,1,0,0,1,0
23,38334871.las,4238334871,"SECTION 18, BLOCK 6",1,1,1,1,0,1,0,0,1,0
24,38334872.las,4238334872,636' FNL & 468' FEL,1,0,1,1,0,0,0,0,1,0
25,38334904.las,4238334904,"SECTION7, BLOCK 6",1,1,1,1,0,1,0,0,1,0
26,38334918.las,4238334918,1950' FNL & 2021' FE,1,0,1,1,0,0,1,0,1,1
27,38334919.las,4238334919,467' FNL & 2430' FEL,1,0,1,1,0,0,1,0,1,1
28,38334927.las,4238334927,1787' FEL & 467' FNL,1,0,1,0,0,0,0,0,0,0
29,38337288_UNIV_LANDS_11_3_1_QUAD_SPECTRAL_LAS.las,4238337288,200' FSL & 200' FEL,1,1,0,0,1,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,4238338364_UNIV_EAST_4325CH_dq1000a_FINAL.las,4238338364,X-1700480 Y-515998,0,0,0,0,0,0,0,0,0,0
522,4238338364_UNIV_EAST_4325CH_dq1000c_FINAL.las,4238338364,X-1700480 Y-515998,0,0,0,0,0,0,0,0,0,0
523,4238338364_UNIV_EAST_4325CH_dq1000d_FINAL.las,4238338364,X-1700480 Y-515998,0,0,0,0,0,0,0,0,0,0
524,8472_1_2.las,4238338158,"224.3' FNL & 1827.7' FWL, SEC 9, BLK 9, UL SURVEY",0,0,0,0,0,0,0,0,0,0
525,8537_1_2.las,4238338214,"2548' FNL & 40' FEL, SEC 9, BLK 49, UL SURVEY,...",0,0,0,0,0,0,0,0,0,0
526,Final.las,4238334861,"SECTION 6, BLOCK 7",0,0,0,0,0,0,0,0,0,0
527,Irst_ic.las,4238334917,2480' FSL & 467' FEL,1,0,0,0,0,0,0,0,0,0
528,LAURA#2.las,NaN,NaN,1,0,0,0,0,0,0,0,0,0
529,main_bhc-hals.las,4238301563,660' FNL & 660' FEL,1,0,0,0,0,1,0,0,0,0
530,main_tld-cnl-mcfl_hires.las,4238301563,660' FNL & 660' FEL,1,0,0,0,0,0,0,0,0,0
531,NUKE_MAIN_DOLO.las,4238301567,"1380' FROM N/L, 1980",1,0,1,0,0,0,0,0,0,0
532,NUKE_MAIN_LIME.las,4238301567,"1380' FROM N/L, 1980",1,0,1,0,0,0,0,0,0,0
533,Pioneer_University_2_28_1_CNL.las,4238336414,"2173' FSL & 660' FEL--Section 28, Block 2--Uni...",1,0,0,0,0,0,0,0,0,0
534,Pioneer_University_2_32_4_CNL.las,4238336712,"660' FSL & 1980' FWL--Sec. 32, Blk. 2, Univers...",1,0,0,0,0,0,0,0,0,0
535,Rep.las,4238334861,"SECTION 6, BLOCK 7",1,1,1,1,1,1,0,0,1,0
536,repeat_bhc-hals.las,4238301563,660' FNL & 660' FEL,1,0,0,0,0,1,0,0,0,0
537,repeat_tld-cnl-mcfl.las,4238301563,660' FNL & 660' FEL,1,0,0,0,0,0,0,0,0,0
538,Rkprop.las,4238334861,"SECTION 6, BLOCK 7",0,0,0,0,0,0,0,0,1,0
539,UNIV 09 #0913H ST2_ML_8361_ST2_2_0.las,4238338151,"1887.6' FWL & 223.1 FNL, SEC. 9, BLK 9, UL SURVEY",0,0,0,0,0,0,0,0,0,0
540,Univ.9#0907H Las.las,4238338158,Reagan Co.,1,0,0,0,0,0,0,0,0,0
541,UNIVERSITY 09 #1802H LAS.las,4238337708,REAGAN COUNTY,1,0,0,0,0,0,0,0,0,0
542,University 09 1802H LAS FINAL.las,4238337708,6066.7' FSL 4288.4' FEL,0,0,0,0,0,0,0,0,0,0
543,University 09#0913H ST2.las,4238338151,REAGAN CO,1,0,0,0,0,0,0,0,0,0
544,University 49 #0911H LAS.las,4238338214,REAGAN CO. TX.,1,0,0,0,0,0,0,0,0,0
545,UNIVERSITY_09_0802H.las,4238337955,"1864' FNL, 2103' FWL",0,0,0,0,0,0,0,0,0,0
546,UNIVERSITY_09_0902H.las,4238337940,"University Lands Block 9,Section 9",0,0,0,0,0,0,0,0,0,0
547,UNIVERSITY_12-12#4_CNL.las,4238335979,"660 FsL & 660 FWL--SEC. 12, BLK. 12, UNIVERSIT...",1,0,0,0,0,0,0,0,0,0
548,UNIVERSITY_2_32_2_CNL_LAS.las,4238336174,"1980' FNL & 1980' FEL--SEC. 32, BLK. 2--UNIVER...",1,0,0,0,0,0,0,0,0,0
549,UNIVRSITY 43-15_6H(5 INCH).las,4238338273,SEC 15 BLOCK 43 ...,0,0,0,0,0,0,0,0,0,0
550,univ_58_19_1_cnl.las,4238336423,"1980' FSL & 660' FWL--Sec. 19, Blk. 58-- Unive...",1,0,0,0,0,0,0,0,0,0

In [98]:
def web_scrape_REAGAN(list_of_apis):
# Define initial dataframe and columns (for REAGAN COUNTY, ELSE THIS WILL CHANGE)
    df = pd.DataFrame(columns = ['API', 
                                 'Website', 
                                 'Block', 
                                 'Section', 
                                 'Latitude', 
                                 'Longitude', 
                                 'Field', 
                                 'Operator'])
# define base url to be added to
    url_frontend = 'http://www.utlands.utsystem.edu/API/'
    for api in list_of_apis:
        full_url = url_frontend + str(api)
# create list instance, first two values of dataframe = api number and url (will use api later to merge dataframes)
        ls = [api, full_url]
# Beautiful Soup get requests > text grabbing        
        page = requests.get(full_url)
        soup = bs(page.content, 'html.parser')
#Some ridiculously ugly code, let's see if it accomplishes the task
        soupstring = str(soup.find_all('tr')[0:1])
        cleantext = bs(soupstring, 'html').get_text().replace('\n', '')
        ls.extend([cleantext[19:21], cleantext[31:33]])
        soupstring = str(soup.find_all('tr')[1:2])
        cleantext = bs(soupstring, 'html').get_text().replace('\n', '')
        ls.extend([cleantext[30:41], cleantext[44:57]])
        if ls[-2] != '':
            if ls[-2][0] == ':':
                ls[-2] = cleantext[31:42]
                ls[-1] = cleantext[45:58]
        else:
            continue
        soupstring = str(soup.find_all('tr')[3:4])
        cleantext = bs(soupstring, 'html').get_text().replace('\n', '')
        ls.extend([cleantext[7:]])
        soupstring = str(soup.find_all('tr')[4:5])
        cleantext = bs(soupstring, 'html').get_text().replace('\n', '')
        ls.extend([cleantext[10:]])
        df.loc[len(df)] = ls     
    return df

In [108]:
def web_scrape_CROCKETT(list_of_apis):
# Define initial dataframe and columns (for REAGAN COUNTY, ELSE THIS WILL CHANGE)
    df = pd.DataFrame(columns = ['API', 
                                 'Website', 
                                 'Block', 
                                 'Section', 
                                 'Latitude', 
                                 'Longitude', 
                                 'Field', 
                                 'Operator'])
# define base url to be added to
    url_frontend = 'http://www.utlands.utsystem.edu/API/'
    for api in list_of_apis:
        full_url = url_frontend + str(api)
# create list instance, first two values of dataframe = api number and url (will use api later to merge dataframes)
        ls = [api, full_url]
# Beautiful Soup get requests > text grabbing        
        page = requests.get(full_url)
        soup = bs(page.content, 'html.parser')
#Some ridiculously ugly code, let's see if it accomplishes the task
        soupstring = str(soup.find_all('tr')[0:1])
        cleantext = bs(soupstring, 'html').get_text().replace('\n', '')
        ls.extend([cleantext[21:23], cleantext[33:35]])
        soupstring = str(soup.find_all('tr')[1:2])
        cleantext = bs(soupstring, 'html').get_text().replace('\n', '')
        ls.extend([cleantext[30:41], cleantext[44:57]])
        if ls[-2] != '':
            if ls[-2][0] == ':':
                ls[-2] = cleantext[31:42]
                ls[-1] = cleantext[45:58]
        else:
            continue
        soupstring = str(soup.find_all('tr')[3:4])
        cleantext = bs(soupstring, 'html').get_text().replace('\n', '')
        ls.extend([cleantext[7:]])
        soupstring = str(soup.find_all('tr')[4:5])
        cleantext = bs(soupstring, 'html').get_text().replace('\n', '')
        ls.extend([cleantext[10:]])
        df.loc[len(df)] = ls     
    return df

In [136]:
reagan_scraped = web_scrape_REAGAN(reagan_list['API'])
crockett_scraped = web_scrape_CROCKETT(crockett_list['API'])

In [137]:
print(reagan_scraped.head(10))
print(crockett_scraped.head(10))

          API                                         Website Block Section  \
0  4238334779  http://www.utlands.utsystem.edu/API/4238334779    06      07
1  4238334779  http://www.utlands.utsystem.edu/API/4238334779    06      07
2  4238334779  http://www.utlands.utsystem.edu/API/4238334779    06      07
3  4238334800  http://www.utlands.utsystem.edu/API/4238334800    06      18
4  4238334800  http://www.utlands.utsystem.edu/API/4238334800    06      18
5  4238334800  http://www.utlands.utsystem.edu/API/4238334800    06      18
6  4238334814  http://www.utlands.utsystem.edu/API/4238334814    07      18
7  4238334815  http://www.utlands.utsystem.edu/API/4238334815    07      05
8  4238334815  http://www.utlands.utsystem.edu/API/4238334815    07      05
9  4238334829  http://www.utlands.utsystem.edu/API/4238334829    07      05

      Latitude      Longitude                                 Field  \
0  31.10055610  -101.68237986  GRIERSON SPRING (STRAWN) (36953500)]
1  31.10055610  -101.68237986  GRIERSON SPRING (STRAWN) (36953500)]
2  31.10055610  -101.68237986  GRIERSON SPRING (STRAWN) (36953500)]
3  31.09595621  -101.68684999             AMIET (STRAWN) (2350600)]
4  31.09595621  -101.68684999             AMIET (STRAWN) (2350600)]
5  31.09595621  -101.68684999             AMIET (STRAWN) (2350600)]
6  31.08238688  -101.66647946  GRIERSON SPRING (STRAWN) (36953500)]
7  31.12296565  -101.64759888  GRIERSON SPRING (STRAWN) (36953500)]
8  31.12296565  -101.64759888  GRIERSON SPRING (STRAWN) (36953500)]
9  31.12260571  -101.64216873  GRIERSON SPRING (STRAWN) (36953500)]

                             Operator
0    APACHE CORPORATION (0000027200)]
1    APACHE CORPORATION (0000027200)]
2    APACHE CORPORATION (0000027200)]
3    APACHE CORPORATION (0000027200)]
4    APACHE CORPORATION (0000027200)]
5    APACHE CORPORATION (0000027200)]
6     THOMPSON, J. CLEO (0000855610)]
7    APACHE CORPORATION (0000027200)]
8    APACHE CORPORATION (0000027200)]
9  MARATHON OIL COMPANY (0000525380)]
          API                                         Website Block Section  \
0  4210541145  http://www.utlands.utsystem.edu/API/4210541145    42      13
1  4210542069  http://www.utlands.utsystem.edu/API/4210542069    06      31
2  4210537385  http://www.utlands.utsystem.edu/API/4210537385    32      18
3  4210537461  http://www.utlands.utsystem.edu/API/4210537461    33      17
4  4210537507  http://www.utlands.utsystem.edu/API/4210537507    42      12
5  4210537798  http://www.utlands.utsystem.edu/API/4210537798    39      19
6  4210537897  http://www.utlands.utsystem.edu/API/4210537897    07      32
7  4210537917  http://www.utlands.utsystem.edu/API/4210537917    07      28
8  4210541148  http://www.utlands.utsystem.edu/API/4210541148    45      21
9  4210537507  http://www.utlands.utsystem.edu/API/4210537507    42      12

      Latitude      Longitude                                  Field  \
0  30.93042300  -101.19696991  HOLT RANCH (CONSOLIDATED) (42341300)]
1  05317222 /     1.68741111]                  WILDCAT (7C) (16001)]
2  30.66447967  -101.36696558      HUNT-BAGGETT (STRAWN) (43675666)]
3  30.67538897  -101.48711849     HOWARDS CREEK (CANYON) (42985500)]
4  30.94624659  -101.19849987  HOLT RANCH (CONSOLIDATED) (42341300)]
5  30.94580912  -101.08700766          BLOCK 39-B (ELLEN) (9422500)]
6  31.04589851  -101.63225856                  WILDCAT (7C) (16001)]
7  31.06754764  -101.64259883                  WILDCAT (7C) (16001)]
8  30.93803733  -101.21513032  HOLT RANCH (CONSOLIDATED) (42341300)]
9  30.94624659  -101.19849987  HOLT RANCH (CONSOLIDATED) (42341300)]

                                        Operator
0           APPROACH OPERATING LLC (0000028625)]
1   GREAT WESTERN DRILLING COMPANY (0000328780)]
2      EPIC PERMIAN OPERATING, LLC (0000253404)]
3                DJH OIL & GAS LLC (0000221734)]
4              EOG RESOURCES, INC. (0000253162)]
5  UNION PACIFIC RESOURCES COMPANY (0000876645)]
6          ENRON OIL & GAS COMPANY (0000253196)]
7                THOMPSON, J. CLEO (0000855610)]
8           APPROACH OPERATING LLC (0000028625)]
9              EOG RESOURCES, INC. (0000253162)]

In [144]:
# merging original dataframes with log info and new dataframes with website info
new_reagan = pd.merge(reagan_list, reagan_scraped, on = 'API')
new_crockett = pd.merge(crockett_list, crocket_scraped, on = 'API')

In [145]:
#create a list in the desired order for the columns of new dataframe
column_order = ['API', 
                 'Website', 
                 'Section', 
                 'Block', 
                 'Latitude', 
                 'Longitude', 
                 'Operator', 
                 'Field', 
                 'GR', 
                 'LLD', 
                 'MSFL', 
                 'DPHI', 
                 'NPHI', 
                 'PE', 
                 'XPHI', 
                 'SPHI',
                 'RHOB',
                 'POTA', 
                 'Filename']

In [146]:
#create the final dataframe, will columns in correct order, original LOC dropped (las file LOC data was terrible)
reagan_final = new_reagan[column_order]
crockett_final = new_crockett[column_order]

In [150]:
reagan_final = reagan_final.drop_duplicates()
crockett_final = crockett_final.drop_duplicates()

In [152]:
reagan_final.to_csv(r'completed_Reagan_county.csv', 
             index = True, 
             header= True)
crockett_final.to_csv(r'completed_Crockett_county.csv', 
             index = True, 
             header= True)